name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Lancer les tests
        run: |
          python -m pytest
        working-directory: src

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Déploiement Docker
        run: |
          echo "🚀 Déploiement de l'application..."
          docker stop my-calculator || true
          docker rm my-calculator || true
          docker build -t labo0-calculator .
          docker run -d --name my-calculator -p 5000:5000 labo0-calculator

      - name: Vérification du conteneur
        run: |
          echo "🔍 Vérification du conteneur..."
          docker ps | grep my-calculator