name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Exécuter les tests
        run: python -m pytest
        working-directory: src

      - name: Debug SSH
        run: |
          echo "Test connexion SSH"
          ssh -vvv -o StrictHostKeyChecking=no -i <(echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}") \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "echo OK"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Déploiement via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            cd /chemin/vers/votre/app/
            git pull
            docker-compose up -d --build
